djangocollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here:

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()

    def __str__(self):
        return f'{self.name} ({self.id})'


def get_absolute_url(self):
    return reverse('detail', kwargs={'finch_id': self.id})


class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )
    
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)
    
    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

        

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


from .models import Finch
from .forms import FeedingForm

# data usually comes from a model; temporary data below for now

# finches = [
#     {'name': 'darwin'},
#     {'name': 'big bird'}
# ]

# Create your views here.
# (views in Django are like controllers in express)

def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {
        'finches': finches
    })

def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch, 'feeding_form': feeding_form
    })

def add_feeding(request, finch_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.finch_id = finch_id
    new_feeding.save()
    return redirect('detail', finch_id=finch_id)


class FinchCreate(CreateView):
    model = Finch
    fields = '__all__'
    success_url = '/finches/'

class FinchUpdate(UpdateView):
  model = Finch
  fields = ['breed', 'description', 'age']
  success_url = '/finches/'

class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches/'

# the {} argument is how python data is passed into this function

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About</h1>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!-- this will pre-cache the static assetts -->




<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Django Collector App</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">&copy; Robert Hayden, MD &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Finch Details</h1>

    <!-- this is NOT embedded python, though it does look like it... this is a django embedded language -->
 
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ finch.name }}</span>
            <span>{{ finch.description | linebreaks }}</span>
            <span>{{ finch.breed | linebreaks }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'finches_update' finch.id %}">Edit</a>
            <a href="{% url 'finches_delete' finch.id %}">Delete</a>
        </div>

        <div class="col s6">
            <form action="{% url 'add_feeding' finch.id %}" method="POST">
                {% csrf_token %}
                {{ feeding_form.as_p }}
                <input type="submit" class="btn" value="Add Feeding">
              </form>
            <table class="striped">
              <thead>
                <tr><th>Date</th><th>Meal</th></tr>
              </thead>
              <tbody>
                {% for feeding in finch.feeding_set.all %}
                  <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
    </div>

<script>
    const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
     });

    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);

</script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>List of All Finches</h1>

    {% for finch in finches %}
    <!-- this is NOT embedded python, though it does look like it... this is a django embedded language -->
    <a href="{% url 'detail' finch.id %}">
        <!-- the name=detail was already provided, which is why this will link! -->
    <div class="card">
        <div class="card-content">
            
            <span class="card-title">{{ finch.name }}</span>
            <span>Description: {{ finch.description | linebreaks }}</span>
        </div>
    </div>
    </a>

    {% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}

  <!-- New if/else block -->
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Finch</h1>
  {% endif %}

  <!-- <h1>Add Finch</h1> -->
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}